DevOpsLearning/DevOpsLearning/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('devops.urls')),
]

DevOpsLearning/devops/urls.py
from django.urls import path
from . import views

app_name = 'devops'

urlpatterns = [
    path('', views.home, name='home'),  # Add this line for the root path
    path('modules/', views.modules, name='modules'),
    path('module/<str:module>/', views.module_lesson, name='module_lesson'),
    path('home/', views.home, name='home'),
]

DevOpsLearning/devops/models.py
from django.db import models

# Create your models here.

DevOpsLearning/devops/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

def modules(request):
    return render(request, 'modules.html')

def module_lesson(request, module):
    return render(request, f'{module}.html')

DevOpsLearning/devops/templates/base.html
<!-- devops/templates/base.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}DevOps Learning{% endblock %}</title>

     <!-- Load the static tag for including static files -->
    {% load static %}


    <!-- Add the Bootstrap stylesheet link here -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <!-- Include your custom CSS file -->
    <link rel="stylesheet" type="text/css" href="{% static 'devops/styles.css' %}">
</head>
<body>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

DevOpsLearning/devops/templates/home.html
<!-- devops/templates/home.html -->
{% extends 'base.html' %}

{% block title %}Welcome DevOps Enthusiast{% endblock %}

{% block content %}
    <h1>Welcome DevOps Enthusiast</h1>
    <a href="{% url 'devops:modules' %}" class="btn btn-primary">Click here to Explore DevOps</a>
{% endblock %}

DevOpsLearning/devops/templates/intro.html
<!-- devops/templates/home.html -->
{% extends 'base.html' %}

{% block title %}Welcome DevOps Enthusiast{% endblock %}

{% block content %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Introduction and Overview</title>
</head>
<body>
    <h1>Introduction and Overview</h1>
    <p>This module provides an introduction to DevOps and an overview of its principles and practices.</p>
    <!-- Add more content as needed -->
</body>
</html>

{% endblock %}

DevOpsLearning/devops/templates/linux.html
<!-- devops/templates/home.html -->
{% extends 'base.html' %}

{% block title %}Welcome DevOps Enthusiast{% endblock %}

{% block content %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Linux for DevOps</title>
</head>
<body>
    <h1>Linux for DevOps</h1>
    <p>This module covers essential Linux commands and concepts relevant to DevOps practices.</p>
    <!-- Add more content as needed -->
</body>
</html>

{% endblock %}

DevOpsLearning/devops/templates/modules.html
<!-- devops/templates/home.html -->
{% extends 'base.html' %}

{% block title %}Welcome DevOps Enthusiast{% endblock %}

{% block content %}

<ul>
  <li><a href="{% url 'devops:module_lesson' 'intro' %}">Introduction and Overview</a></li>
  <li><a href="{% url 'devops:module_lesson' 'linux' %}">Linux for DevOps</a></li>
  <li><a href="{% url 'devops:module_lesson' 'git' %}">Git</a></li>
  <!-- Add other modules as needed -->
</ul>


{% endblock %}